### PR TITLE
added requesting of permission to show() and missed callbacks allocations

### PR DESCRIPTION
**Pull request by slr**

### CODE REVIEW

**Comment by alexgibson** [comment]
Thanks for the PR!

It looks like you have hit on the readme being a bit out of date I think. Once upon a time, `requestPermission` used to be on the `prototype` chain. However we changed it to a static method, as the former behavior meant you had to create a new `Notify` instance just to query user permission levels. In older versions of Chrome, user permission could also not be initiated via `show()`, it had to be via a click or user initiated event. This has been fixed now in Chrome 37.

Your change here would work, however I still think there's merit in not tying `requestPermission` to the `prototype` as it stands currently, i.e. permission is better handled *before* creating a notificaton. Thoughts? Any reason why you **need** this change for your usage?

I am also fine with `show()` triggering an error if permission has not been granted. This is what the error callback is for, as per the spec.

**Comment by slr** [comment]
I have no any significant reason. I just got it wrong. thanks for comprehensive answer!

I think we need to have complete example of best practice of notification handling in readme. Is it something like that?

    if (Notify.isSupported) {
        if (Notify.needsPermission) {
            requestPermission(onNotifyPermissionGranted, onNotifyPermissionDenied);
        }

        if (!Notify.needsPermission) {
            var myNotification = new Notify('Yo dawg!', {
                body: 'This is an awesome notification',
                notifyShow: onNotifyShow
                notifyError: onNotifyPermissionDenied
            });
                myNotification.show();
        }
    }

    function onNotifyPermissionGranted() {
        console.log('permission granted!');
    }

    function onNotifyPermissionDenied() {
        console.log('permission denied!');
    }

    function onNotifyShow() {
        console.log('notification was shown!');
    }

and why do options permissionGranted and permissionDenied exist in Notify() if they do not used?

**Comment by alexgibson** [comment]
No problem, and you are totally right I should make the demo example more visible (see the hg-pages branch here https://github.com/alexgibson/notify.js/tree/gh-pages). I think I will move this into an `examples` folder in master.

And you are correct I need to remove those two options from Notify since they are no longer used. I'll see to doing this very soon. Thanks for the reminder and sorry if this caused some confusion.

**Comment by slr** [comment]
OK and thank you!

**Comment by alexgibson** [comment]
Removed the two redundant permissionGranted and permissionDenied options and tagged [v1.2.5](https://github.com/alexgibson/notify.js/releases/tag/v1.2.5). Going to close this PR now, thanks.

I also opened a [new issue](https://github.com/alexgibson/notify.js/issues/33) as a reminder that I should include a basic usage example in the master repo.

**Pull request closed without merging**
