### PR TITLE
Migrate source to ES6

### PR DESCRIPTION
**Pull request by perrin4869**
Tests pass, hope you like this!

### CODE REVIEW

**Comment by alexgibson** [comment]
Thanks! I'll take a look at this and pull it soon - out of curiosity, what kind of module output does this transpile to? Currently we support the UMD pattern to try and be flexible, but I would personally favor moving to a common module. We'd just need to make sure people are aware of the change.

**Comment by perrin4869** [comment]
It outputs UMD, generated by `jspm`, with this command:

```bash
jspm build notifyjs dist/notify.js --format umd --global-name Notify --skip-source-maps
```

You can configure this further if you want too :)

Btw, I can also configure `eslint` with `airbnb` configuration, what do you think about it?

**Comment by alexgibson** [comment]
Great, thanks!

I plan to add ESLint soon, just with my own set of preferences (but thanks for the offer!). I'll see if i can merge this later today :+1:

**Comment by perrin4869** [comment]
You can change `--format umd` to `--format cjs` for a common module.
Cool, when you configure eslint, you can add a `prebuild` script in `package.json`, like this:

```json
"scripts": {
    ...
    "lint": "eslint src/notify.js",
    "prebuild": "npm run lint",
    ...
}
```

**Comment by alexgibson** [comment]
Looks great, many thanks!

**Comment by alexgibson** [comment]
Tested this locally and it works great, r+!

**Pull request merged**
